version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Настройте порт вашего приложения
    environment:
      SPRING_DATASOURCE_URL: jdbc:h2:mem:testdb # Пример для H2; обновите для других баз
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: onlinebank
    ports:
      - "5432:5432"
